### ISSUE TITLE
Material specifications needed

### ISSUE THREAD

**Issue by madhunm** [tanaes/whopping_Voron_mods#2]
Hello,

I would like to make a set of these kinematic bed mounts by myself.

Can you please list the material specifications and the thickness of all the parts?

Thanks!

**Comment by barecool** [comment]
[See v24_kinematic_BOM.md](https://github.com/tanaes/whopping_Voron_mods/blob/main/kinematic_bed/v24_kinematic_BOM.md)

**Comment by MoellerLab** [comment]
thanks @barecool !

**Comment by tanaes** [comment]
thanks @barecool !
