### ISSUE TITLE
Can't open F3Z nor DXF

### ISSUE THREAD

**Issue by vjeko2404** [tanaes/whopping_Voron_mods#6]
Hi,

i don't know if the files are corrupt but I cant seem to opet the DXF or F3Z file.
There is no possible way for me to know the dimensions of the backers without opening one of those two files.
Could you check it out?

Thanks!

**Comment by tanaes** [comment]
They seem to work fine for me. GitHub can be weird about downloading files. If you clone the repository, can you open them then?

**Comment by vjeko2404** [comment]
Thank you for your answer!
I have found out that my maschine-software was outdatet. After upgrading on the latest version, everything worked fine!
I'm closing the issue!
